### ISSUE TITLE
Takes forever to load lights list

### ISSUE THREAD

**Issue by Sawtaytoes** [futomi/node-lifx-lan#10]
I was noticing this library takes forever to load my lights list vs the `node-lifx` package. I figured it might be because `node-lifx` gives you lights as it finds them whereas `node-lifx-lan` gives the final device list at the end. I have 113 LIFX lights with more coming in the future. I think the problem occurs because it takes so long to find all of them in my network.

I think I tracked the problem down to `lifx-lan-udp.js` where it's setting up timers and waits.

Is it possible we could have another `.discover` method that's async and rename this one to `discoverSync` similar to Node.js native libraries?

**NOTE:** I tested this library on a Raspberry Pi running Raspbian.

**Comment by Sawtaytoes** [comment]
Closing this for now until I get more info.

**Comment by Sawtaytoes** [comment]
Ok, I confirmed this is happening now on Windows as well. Something to do with the timers, it's waiting for all the lights to come back within a certain timeframe, then returning the entire list.

Just this little bit of code from the docs took over 5 min to run, and I canceled it after that because I didn't want to wait any longer:
```js
const Lifx	= require('node-lifx-lan');

Lifx.discover().then((device_list) => {
	device_list.forEach((device) => {
		console.info([
			device['ip'],
			device['mac'],
			device['deviceInfo']['label']
		].join(' | '));
	});
}).catch((error) => {
	console.error(error);
});
```

**Comment by futomi** [comment]
Sorry for being late.

You have 113 LIFX lights? Wow!
Unfortunately, I didn't assume that there are so many lights in a local network.

As you know, the reason why the `discover()` method takes so long time in your environment is because the method fetches device information from each found device sequentially after the discovery process. 

I will try to re-design the discovery process. But I'm not sure when I can do that. Sorry about that.

**Comment by Sawtaytoes** [comment]
No problem. I'll figure something out in the meantime. I appreciate you looking into my issues!

I'm sure I'm an outlier with so many lights so no rush.
